### ISSUE TITLE
Cant get app to work 

### ISSUE THREAD

**Issue by ghost** [andriy921/Simple-Twitch#1]
Hi! First thanks for the work! :D Iam a doto player too! :)

So, i want to try your app but iam not smart enough for my smart tv XD

First Question:
Do i copy the just the first folder to my usb stick or do i have to copy another one?
(i tried some but none work :( )

2nd:
Do i have to start the "smart tv" function or the app button?

3rd:
Is there maybe a special option in the settings that blocks 3rd party apps?

thx :)

**Comment by astashko** [comment]
Hi.
1. Take latest version of app (currently it's 0.1.0). Download zip file.
Extract it's content to the root of the usb drive. Turn off tv. Input usb
drive into it. Turn on tv.
2. The app should appear in your apps list. You can access it via apps
button or smart+scroll to right.
3. There is no such function. But you should be logged in into LG store on
your tv.

Please give me your tv model and path to index.html file on your usb drive.
Waiting for your responce.

**Comment by ghost** [comment]
Hi,
i tried your instruction but it didnt work .. but iam not sure i did everything correct, so..yea :)

This is my TV Model: LG 55LB580V
And the path to Index.html: E:\apps\usr\palm\applications\com.andriy921.app.simpletwitch

PS: i was logged into my lg store account and turn tv off and on :) but there was no twitch app :/

**Comment by astashko** [comment]
It should be E:\developer\apps\usr\palm\applications\com.andriy921.app.simpletwitch

**Comment by ghost** [comment]
Thank you :) I try it again now!

Am 11.06.2015 um 22:37 schrieb andriy921:

**Comment by ghost** [comment]
So, i try now but it doesnt work. 

I change the path on my usb stick, then i turn tv off, plug usb in, turn tv on. 
I start the smart tv function and at "Premium (youtube ect.)" no app... at "My apps" also no app :(

I dont understand this :( where is my mistake?! or is it the tv?

**Comment by astashko** [comment]
It looks like your tv is not web os based. It's probably netcast.

**Comment by ghost** [comment]
I did a little research and that seems to be the issue.. sad, but thank you for your fast response!
