### ISSUE TITLE
Can't see the App

### ISSUE THREAD

**Issue by majuss** [andriy921/Simple-Twitch#2]
Hello there! I'am really glad to the an App like that in developement :+1: :)
Thank you for the freetime you are sacrificing! If it works well in the future I would even donate for this!

But here is my problem:
This is my TV: LG 55UC970V running WebOS 2.0 newest version.

I downloaded the .zip and extracted it onto the USB drive: 
Volumes/UNTITLED\ 2/developer/apps/usr/palm/applications/com.andriy921.app.simpletwitch/ 
But the TV can't see the app..

Thanks for the help!

**Comment by astashko** [comment]
I guess you have mac, right?
Path seems to be correct. You should check if tv recognizes usb drive at all. And if you are logged in into lg market on your tv.

**Comment by majuss** [comment]
The Stick is formatted as fat32 with a MBR the TV recognizes him and Iam logged in into the store.. Maybe its because the TV is only 8 months on the market?

**Comment by astashko** [comment]
It shouldn't meter. App is for both 2014 and 2015 models.

**Comment by ghost** [comment]
Maybe the same issue as my? Is the operating system webOS?

Von meinem iPhone gesendet

**Comment by astashko** [comment]
Have you tried to turn on/off with usb stick in tv? The app doesn't automatically appear in the smart menu since it starts with "S" so you should search for it in the app list.
Try if you can install this app: http://obovse.ru/forkplayer/lg_forkplayer.rar . I want to know if the problem is in my app.

**Comment by majuss** [comment]
So I copied the forkplayer to the USB drive and I can see and start it. But your app isn't visible :(

**Comment by astashko** [comment]
I was sick and completely forgot about your issue. Sorry!
So, basically, on the usb drive you have folder "developer\apps\usr\palm\applications\" containing two folders: "com.yourdomain.forkplayer" and "com.andriy921.app.simpletwitch", right?

**Comment by astashko** [comment]
And forkplayer is visible, but simpletwitch not, right?

**Comment by majuss** [comment]
Yes that's exactly the point.

**Comment by chrisban** [comment]
This is still happening to me! Can't see anything in the app list.

**Comment by vfreitas-** [comment]
This is happening to me too! Any solutions?
- webOs 2.0 -

**Comment by lucipacurar** [comment]
on LG webOS 1.4, the app shows up, but it doesn't start when you click it.

**Comment by majuss** [comment]
Follow this:

"Log out
Restart TV
Log in
Restart TV
Try to start app, worked for me"

Thanks to Simpleguy12, works very well!

**Comment by lucipacurar** [comment]
@majuss Will try that, thanks!

**Comment by chrisban** [comment]
@majuss What do you mean by log out? I am having the same issues as lucassp

**Comment by Simpleguy12** [comment]
Go to settings and sour account info. Then log out of your lg store account
@majuss nice good to hear my advice worked for you as well! I think webos is a bit buggy

@rest: developer apps only start when you have an account and you are logged in! (I dont know why its retared i know)

@majuss is your TV really running webos 2.0? I have the same (55uc970v)but my is running 1.4xx.

**Comment by chrisban** [comment]
@Simpleguy12 "developer apps only start when you have an account and you are logged in!"

That's what did it for me, thanks.

**Comment by majuss** [comment]
Mine is running 1.4 also. You have to log out from the LG-Store you will find this option by "Account-Settings" in the settings-menu not in the store app.

**Comment by lucipacurar** [comment]
I logged in and logged out a couple of times and the app still won't start. I can see the app in the menu, it has the Enyo framework logo, click it and nothing happens. I have an LG 42LB671v. Can I somehow debug this using the WebOS SDK?

**Comment by lucipacurar** [comment]
After a couple more restarts, it worked. And the fix from #8 made it actually play the streams. Thanks!

**Comment by ghost** [comment]
Don't see the app so maybe I should try that. A few questions related to this, that could go into the wiki howto:
- does running it require a LG developer account?
- can the app be installed, ie you don't need the usb drive?

**Comment by chrisban** [comment]
@kurosu 
It requires an account to be logged in, not a dev account.
As for the usb drive, as far as I know you can't install it. You need the usb.
