### ISSUE TITLE
Download link to dropbox is dead.

### ISSUE THREAD

**Issue by optiguy** [andriy921/Simple-Twitch#9]
The download page :
https://github.com/astashko/Simple-Twitch/wiki/Download

Has a dead link to a distribution version 0.1.0 :
https://www.dropbox.com/s/2gmstguae1udpiq/simpletwitch_v_0_1_0.zip?dl=0

**Comment by Eduardomb22** [comment]
anyone can fix this? pls

**Comment by majuss** [comment]
This App doesnt work at all. Its useless. Just use: https://github.com/astashko/Simple-Twitch

Use the recent code form the repo (git clone) not the old download link.
